pipeline {
    agent any

    environment {
        PYTHON_VERSION = '3.12'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Setup Python') {
            steps {
                sh '''
                echo "PATH=$PATH"
                which python3 || true
                which pip3 || true
                python3 --version
                python3 -m pip --version
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('employee-payroll-management-system') {
                    sh '''
                    python3 -m venv venv
                    . venv/bin/activate

                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Lint') {
            steps {
                dir('employee-payroll-management-system') {
                    sh '''
                    . venv/bin/activate
                    flake8 . --extend-ignore=W292,W293
                    '''
                }
            }
        }

        stage('Execute Application') {
            steps {
                dir('employee-payroll-management-system') {
                    sh '''
                    . venv/bin/activate
                    printf "John\n50000\n" | python app.py
                    '''
                }
            }
        }

        stage('Run Unit Tests') {
            steps {
                dir('employee-payroll-management-system') {
                    sh '''
                    . venv/bin/activate
                    pytest -v
                    '''
                }
            }
        }
    }
}