name: CI/CD Pipeline.

on:
  push:
    branches:
      - main
  

jobs:
  build:
    runs-on:
      - self-hosted
      - Linux

    steps:
      - uses: actions/checkout@v4

      - name: Verify Runner
        run: |
          hostname
          whoami
          pwd
          dotnet --info

    
      - name: Restore Dependencies
        run: dotnet restore MyDotNetApp.csproj

      - name: Build Application
        run: dotnet build MyDotNetApp.csproj --configuration Release --no-restore

      
