name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on:
      - self-hosted
      - Linux

    steps:

      - uses: actions/checkout@v4

      - name: Verify Runner
        run: |
          hostname
          whoami
          pwd
          dotnet --info

      - name: Restore
        run: |
          dotnet restore MyDotNetApp.csproj
          dotnet restore MyDotNetApp.Tests/MyDotNetApp.Tests.csproj

      - name: Build
        run: |
          dotnet build MyDotNetApp.csproj --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test MyDotNetApp.Tests/MyDotNetApp.Tests.csproj --no-restore --logger trx