name: Employee Payroll CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    environment: development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Runner
        run: |
          hostname
          whoami
          pwd

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Install Dependencies
        working-directory: employee-payroll-management-system
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Python Code
        working-directory: employee-payroll-management-system
        run: |
          flake8 . --extend-ignore=W292,W293

      - name: Execute Application
        working-directory: employee-payroll-management-system
        run: |
          printf "${{ vars.EMPLOYEE_NAME }}\n${{ vars.BASIC_SALARY }}\n" | python app.py

      - name: Run Unit Tests
        working-directory: employee-payroll-management-system
        run: |
          pytest -v