name: Employee Payroll CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Runner
        run: |
          echo "========== Runner Information =========="
          hostname
          whoami
          pwd
          python3 --version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        working-directory: employee-payroll-management-system
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Python Code
        working-directory: employee-payroll-management-system
        run: |
          flake8 . --extend-ignore=W292

      - name: Execute Application
        working-directory: employee-payroll-management-system
        run: |
          printf "John\n50000\n" | python app.py

      - name: Run Unit Tests
        working-directory: employee-payroll-management-system
        run: |
          pytest -v